server:
  port: 9000
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1

    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 2

  flyway:
    datasources:
      default:
        enabled: true
        locations: 'classpath:db/migration'